
CREATE TABLE USER (
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    UPDATE_DATETIME DATETIME NOT NULL,
    UPDATE_USER VARCHAR(200) NOT NULL,
    VERSION_NO BIGINT NOT NULL
)